### ISSUE TITLE
A problem when implement dockQ, /evaluate/DockQ/scripts is not exist.

### ISSUE THREAD

**Issue by Ming-Qin-tech** [yaledeus/ElliDock#12]
After download DockQ from https://github.com/bjornwallner/DockQ.git.
their are "examples  LICENSE  pyproject.toml  README.md  run_test.sh  setup.cfg  setup.py  src  testdata  update_testdata.sh" exist.
But your evaluate/dockq.py needs 
FILE_DIR = os.path.split(__file__)[0]
FIXEXEC = os.path.join(FILE_DIR, 'DockQ', 'scripts', 'fix_numbering.pl')
DQEXEC = os.path.join(FILE_DIR, 'DockQ', 'DockQ.py')
CACHE_DIR = os.path.join(FILE_DIR, '__dqcache__')

obviously there is no "/scripts" and "fix_numbering.pl" exists, nor "\Dock" and "\DockQ\DockQ.py" .  Could you provide the folder of Dock you used cuz it seems like you have modified it which is different from https://github.com/bjornwallner/DockQ.git. Please provide it so that we can reimplement this interesting work!

**Comment by yaledeus** [comment]
I found a version change of DockQ src code in https://github.com/bjornwallner/DockQ.git a few weeks ago. Maybe you can try the old version in https://github.com/bjornwallner/DockQ/releases/tag/v1.0.

**Comment by Ming-Qin-tech** [comment]
OK， thx！ I'll check it right now!   good night!
